function [fitresult, gof] = createFit(age_sorted, SD_age_wise)
%CREATEFIT(AGE_SORTED,SD_AGE_WISE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : age_sorted
%      Y Output: SD_age_wise
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Nov-2016 19:23:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( age_sorted, SD_age_wise );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'SD_age_wise vs. age_sorted', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'age_sorted' );
ylabel( 'SD_age_wise' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( 'age_sorted' );
ylabel( 'SD_age_wise' );
grid on


